# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: oink 0.10.1 ruby lib

Gem::Specification.new do |s|
  s.name = "oink".freeze
  s.version = "0.10.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Noah Davis".freeze]
  s.date = "2019-03-14"
  s.description = "Log parser to identify actions which significantly increase VM heap size".freeze
  s.email = "noahd1@yahoo.com".freeze
  s.executables = ["oink".freeze]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "bin/oink",
    "lib/oink.rb",
    "lib/oink/cli.rb",
    "lib/oink/instrumentation.rb",
    "lib/oink/instrumentation/active_record.rb",
    "lib/oink/instrumentation/memory_snapshot.rb",
    "lib/oink/middleware.rb",
    "lib/oink/parsers.rb",
    "lib/oink/parsers/hodel_parser.rb",
    "lib/oink/parsers/stdlib_parser.rb",
    "lib/oink/rails.rb",
    "lib/oink/rails/instance_type_counter.rb",
    "lib/oink/rails/memory_usage_logger.rb",
    "lib/oink/reports/active_record_instantiation_oinked_request.rb",
    "lib/oink/reports/active_record_instantiation_report.rb",
    "lib/oink/reports/base.rb",
    "lib/oink/reports/memory_oinked_request.rb",
    "lib/oink/reports/memory_usage_report.rb",
    "lib/oink/reports/priority_queue.rb",
    "lib/oink/reports/request.rb",
    "lib/oink/utils/hash_utils.rb"
  ]
  s.homepage = "http://github.com/noahd1/oink".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.7.6".freeze
  s.summary = "Log parser to identify actions which significantly increase VM heap size".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hodel_3000_compliant_logger>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<activerecord>.freeze, [">= 0"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_development_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_development_dependency(%q<sqlite3>.freeze, [">= 0"])
      s.add_development_dependency(%q<rack-test>.freeze, [">= 0"])
      s.add_development_dependency(%q<rake>.freeze, [">= 0"])
      s.add_development_dependency(%q<ruby-debug>.freeze, [">= 0"])
      s.add_development_dependency(%q<debugger>.freeze, [">= 0"])
    else
      s.add_dependency(%q<hodel_3000_compliant_logger>.freeze, [">= 0"])
      s.add_dependency(%q<activerecord>.freeze, [">= 0"])
      s.add_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_dependency(%q<sqlite3>.freeze, [">= 0"])
      s.add_dependency(%q<rack-test>.freeze, [">= 0"])
      s.add_dependency(%q<rake>.freeze, [">= 0"])
      s.add_dependency(%q<ruby-debug>.freeze, [">= 0"])
      s.add_dependency(%q<debugger>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<hodel_3000_compliant_logger>.freeze, [">= 0"])
    s.add_dependency(%q<activerecord>.freeze, [">= 0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    s.add_dependency(%q<rspec>.freeze, [">= 0"])
    s.add_dependency(%q<sqlite3>.freeze, [">= 0"])
    s.add_dependency(%q<rack-test>.freeze, [">= 0"])
    s.add_dependency(%q<rake>.freeze, [">= 0"])
    s.add_dependency(%q<ruby-debug>.freeze, [">= 0"])
    s.add_dependency(%q<debugger>.freeze, [">= 0"])
  end
end

